### ISSUE TITLE
Covert this repo to a monorepo

### ISSUE THREAD

**Issue by NeekSandhu** [NeekSandhu/aspen#1]
Have all the core deps live in one place using lerna monorepo setup:

Core deps like:
 - [aspen-tree-model](https://github.com/NeekSandhu/aspen-tree-model)
 - [aspen-core](https://github.com/NeekSandhu/aspen-core)
 - [aspen-decorations](https://github.com/NeekSandhu/aspen-decorations)

Maybe also rename this repo from `react-aspen` to just `aspen`.

**Comment by LoganDark** [comment]
> Maybe also rename this repo from `react-aspen` to just `aspen`.

https://www.npmjs.com/package/aspen - published 9 years ago.

**Comment by NeekSandhu** [comment]
oopsy poopsy! I guess the renaming part will be left out.

Also, the issue itself might look stale since it's very old, but ironically I'm just about to begin the refactoring in about 2-3 weeks. It had been put on standby this entire time, but now that this package getting a bit of traction, it's about time it gets touched up.

**Comment by LoganDark** [comment]
> Also, the issue itself might look stale since it's very old, but ironically I'm just about to begin the refactoring in about 2-3 weeks. It had been put on standby this entire time, but now that this package getting a bit of traction, it's about time it gets touched up.

This could also help with your SEO issue. If you update the library and share it around, it could gain a boost in the currently-horrid search rankings.

**Comment by NeekSandhu** [comment]
Included in the [Aspen 2 milestone](https://github.com/NeekSandhu/aspen/issues/19).
